//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Order_id { get; set; }
        public int Order_dataId { get; set; }
        public int Order_productId { get; set; }
        public int Order_count { get; set; }
    
        public virtual OrderData OrderData { get; set; }
        public virtual Products Products { get; set; }
    }
}
