//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderData()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int OrderData_id { get; set; }
        public System.DateTime OrderData_data { get; set; }
        public System.DateTime OrderData_endData { get; set; }
        public int OrderData_pickUpPoint { get; set; }
        public int OrderData_user { get; set; }
        public int OrderData_code { get; set; }
        public string OrderData_status { get; set; }
    
        public virtual PickUpPoints PickUpPoints { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
